services:
  - type: web
    name: right-to-music
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      export PORT=${PORT:-5000}
      python3 main.py serve --proto http -p $PORT
    plan: free
    autoDeploy: true

  - type: web
    name: audio-matcher
    env: node
    rootDir: Project/client
    buildCommand: |
      npm install
      npm run build
    startCommand: npx serve -s build
    plan: free
    autoDeploy: true
