services:
  - type: web
    name: Right-To-Music
    env: python
    plan: free
    rootDir: Project/server
    buildCommand: pip install -r requirements.txt
    startCommand: |
      # export PORT=${PORT:-5000}
      python3 main.py serve --proto https -p ${PORT:-5000}
      # python3 main.py serve --proto http -p $PORT
    envVars:
      - key: FLASK_ENV
        value: production

  - type: web
    name: audio-matcher
    env: node
    rootDir: Project/client
    buildCommand: |
      npm install
      npm run build
    startCommand: npx serve -s build
    plan: free
    autoDeploy: true
