services:
  - type: web
    name: right-to-music-backend
    env: python
    buildCommand: ""
    startCommand: |
      export PORT=${PORT:-5000}
      cd server
      python3 main.py serve --proto http -p $PORT
    plan: free
    autoDeploy: true

  - type: web
    name: right-to-music-frontend
    env: node
    rootDir: client
    buildCommand: |
      npm install
      npm run build
    startCommand: serve -s build
    staticPublishPath: client/build
    plan: free
    autoDeploy: true
